#!/bin/sh

# Displays number of upgradeable packages.
# For this to work, have a `pacman -Sy` command run in the background as a
# cronjob every so often as root. This script will then read those packages.
# When clicked, it will run an upgrade via pacman.
#
# Add the following text as a file in /usr/share/libalpm/hooks/statusbar.hook:
#
# [Trigger]
# Operation = Upgrade
# Type = Package
# Target = *
#
# [Action]
# Description = Updating statusbar...
# When = PostTransaction
# Exec = /usr/bin/pkill -RTMIN+8 dwmblocks
case $UI_ICON in
	emoji) ICON='📦' ;;
	nerd | *) ICON=' ';;
esac

case $BLOCK_BUTTON in
	1) $TERMINAL -e popupgrade ;;
	2) notify-send "$(pacman -Qu)" ;;
	3) notify-send "Upgrade module  "$ICON": number of upgradable packages
- Left click to upgrade packages
- Middle click to show upgradable packages" ;;
esac

pacman -Qu | grep -v "\[ignored\]" | wc -l | sed "s/^/$ICON/;s/^$ICON0$//g"
