#!/bin/sh
# vim: filetype=sh
#
# Description:	Universal interactive shell-startup.
#
# put your aliases here
#

# If not running interactively, don't do anything
[ "$-" = "${-%i*}" ] && return

# Load shortcuts
SHORTCUT=$XDG_CACHE_HOME/shortcutrc
[ -f "$SHORTCUT" ] && . "$SHORTCUT"
#---- less colors for man pages ------------------------------------------------
export LESS_TERMCAP_mb=$'\E[5;93m'	# Begin blinking -> Bright Yellow
export LESS_TERMCAP_md=$'\E[1;94m'	# Begin Bold -> Bright Blue
export LESS_TERMCAP_me=$'\E[0m'		# End mode
export LESS_TERMCAP_se=$'\E[0m'		# End standout-mode
export LESS_TERMCAP_so=$'\E[105;30m'	# Begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'		# End underline
export LESS_TERMCAP_us=$'\E[4;92m'	# Begin underline -> Bright Green
#---- Aliases ------------------------------------------------------------------
unalias lsd 2>/dev/null
#-------- base -------------------------
alias	\
	cp='cp -v'		    \
	diff='diff --color=auto'    \
	grep='grep -E --color=auto' \
	info='info --vi-keys'	    \
	ka='killall'		    \
	l='ls -1'		    \
	la='ls -a'		    \
	ll='ls -l'		    \
	ls='ls --group-directories-first -X --human-readable --color=auto'	\
	lsmovies='(ls /media/sdc5/sobh/movies; ls $HOME/movies;)'		\
	mkd='mkdir -pv'		    \
	mv='mv -v'		    \
	qmv='qmv -f destination-only'   \
	rm='rm -v'		    \

#-------- Preferred Apps ---------------
alias	\
	e='$EDITOR'	\

#-------- git --------------------------
alias \
	ga='git add'	\
	gc='git commit'	\
	gd='git diff'	\
	gs='git status'	\

#-------- pacman -----------------------
alias	\
	p='pacman'		\
	pu='sudo pacman -Syu'	\
	pq='pacman -Q'		\
	po='pacman -Qo'		\

poc(){ pacman -Qo $(which $1); }	# Package Owns Command
