#!/bin/sh
# vim: filetype=sh
#
# Description:	Universal interactive shell-startup.
#
# put your aliases here
#

# if in a terminal
if [ -t 0 ]; then
#	echo "Executing: shell interactive startup."
	# other users shouldn't be able to message by default
	mesg n

	# enable colours
	#if [ `tput colors` -ge 8 ]; then
	#fi
fi
