#!/bin/sh
# vim: filetype=sh
#
# Description:	Universal login shell-startup.
#
# Put your environment variables here
#

# Load Linux Console colors
_color_theme="$XDG_CONFIG_HOME/xresources/colors/sobh.Xresources"
if [ "$TERM" = "linux" ] && [ -f "$_color_theme" ] ; then
	load_console_colors "$_color_theme"
fi
unset _color_theme

# Start ssh-agent
eval $(ssh-agent)
