#!/bin/sh
# vim: filetype=sh
#
# Description:	Universal shell logout script.
#

# When leaving the console, clear the screen to increase privacy
if [ "$SHLVL" = 1 ]; then
    command -v clear &> /dev/null && clear
fi

# Kill the ssh-agent process that was started in the 'login' script
kill $SSH_AGENT_PID
